//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1 版自动生成。
// 
#pragma warning disable 1591

namespace ChinaPay.B3B.Service.ExternalPlatform._51bookMatchPolicy {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GetPolicyByPnrTxtServiceImpl_1_0ServiceSoapBinding", Namespace="http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(abstractLiantuoReply))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(abstractLiantuoRequest))]
    public partial class GetPolicyByPnrTxtServiceImpl_1_0Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getPolicyByPnrTxtOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GetPolicyByPnrTxtServiceImpl_1_0Service() {
            this.Url = global::ChinaPay.B3B.Service.ExternalPlatform.Properties.Settings.Default.ChinaPay_B3B_Service_ExternalPlatform__51bookMatchPolicy_GetPolicyByPnrTxtServiceImpl_1_0Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getPolicyByPnrTxtCompletedEventHandler getPolicyByPnrTxtCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/", ResponseNamespace="http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public getPolicyByPnrTxtReply getPolicyByPnrTxt([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] getPolicyByPnrTxtRequest request) {
            object[] results = this.Invoke("getPolicyByPnrTxt", new object[] {
                        request});
            return ((getPolicyByPnrTxtReply)(results[0]));
        }
        
        /// <remarks/>
        public void getPolicyByPnrTxtAsync(getPolicyByPnrTxtRequest request) {
            this.getPolicyByPnrTxtAsync(request, null);
        }
        
        /// <remarks/>
        public void getPolicyByPnrTxtAsync(getPolicyByPnrTxtRequest request, object userState) {
            if ((this.getPolicyByPnrTxtOperationCompleted == null)) {
                this.getPolicyByPnrTxtOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPolicyByPnrTxtOperationCompleted);
            }
            this.InvokeAsync("getPolicyByPnrTxt", new object[] {
                        request}, this.getPolicyByPnrTxtOperationCompleted, userState);
        }
        
        private void OngetPolicyByPnrTxtOperationCompleted(object arg) {
            if ((this.getPolicyByPnrTxtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPolicyByPnrTxtCompleted(this, new getPolicyByPnrTxtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/")]
    public partial class getPolicyByPnrTxtRequest : abstractLiantuoRequest {
        
        private int allowSwitchPnrField;
        
        private bool allowSwitchPnrFieldSpecified;
        
        private int needSpePricePolicyField;
        
        private bool needSpePricePolicyFieldSpecified;
        
        private int needSpeRulePolicyField;
        
        private bool needSpeRulePolicyFieldSpecified;
        
        private int onlyOnWorkingField;
        
        private bool onlyOnWorkingFieldSpecified;
        
        private string param1Field;
        
        private string param2Field;
        
        private string param3Field;
        
        private string param4Field;
        
        private string pataTxtField;
        
        private string pnrTxtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int allowSwitchPnr {
            get {
                return this.allowSwitchPnrField;
            }
            set {
                this.allowSwitchPnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool allowSwitchPnrSpecified {
            get {
                return this.allowSwitchPnrFieldSpecified;
            }
            set {
                this.allowSwitchPnrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int needSpePricePolicy {
            get {
                return this.needSpePricePolicyField;
            }
            set {
                this.needSpePricePolicyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool needSpePricePolicySpecified {
            get {
                return this.needSpePricePolicyFieldSpecified;
            }
            set {
                this.needSpePricePolicyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int needSpeRulePolicy {
            get {
                return this.needSpeRulePolicyField;
            }
            set {
                this.needSpeRulePolicyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool needSpeRulePolicySpecified {
            get {
                return this.needSpeRulePolicyFieldSpecified;
            }
            set {
                this.needSpeRulePolicyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int onlyOnWorking {
            get {
                return this.onlyOnWorkingField;
            }
            set {
                this.onlyOnWorkingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool onlyOnWorkingSpecified {
            get {
                return this.onlyOnWorkingFieldSpecified;
            }
            set {
                this.onlyOnWorkingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param3 {
            get {
                return this.param3Field;
            }
            set {
                this.param3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param4 {
            get {
                return this.param4Field;
            }
            set {
                this.param4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pataTxt {
            get {
                return this.pataTxtField;
            }
            set {
                this.pataTxtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pnrTxt {
            get {
                return this.pnrTxtField;
            }
            set {
                this.pnrTxtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getPolicyByPnrTxtRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/")]
    public abstract partial class abstractLiantuoRequest {
        
        private string agencyCodeField;
        
        private string signField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string agencyCode {
            get {
                return this.agencyCodeField;
            }
            set {
                this.agencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign {
            get {
                return this.signField;
            }
            set {
                this.signField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/")]
    public partial class wsPolicyData {
        
        private string airlineCodeField;
        
        private string arrivalExcludeField;
        
        private string commentField;
        
        private double commisionMoneyField;
        
        private bool commisionMoneyFieldSpecified;
        
        private float commisionPointField;
        
        private bool commisionPointFieldSpecified;
        
        private string departureExcludeField;
        
        private string expiredDateField;
        
        private string flightCourseField;
        
        private string flightCycleField;
        
        private string flightNoExcludeField;
        
        private string flightNoIncludingField;
        
        private int needSwitchPNRField;
        
        private bool needSwitchPNRFieldSpecified;
        
        private string param1Field;
        
        private string param2Field;
        
        private string param3Field;
        
        private string param4Field;
        
        private string policyBelongToFlagField;
        
        private int policyIdField;
        
        private bool policyIdFieldSpecified;
        
        private string policyTypeField;
        
        private string printTicketExpiredDateField;
        
        private string printTicketStartDateField;
        
        private int productTypeField;
        
        private bool productTypeFieldSpecified;
        
        private string routeTypeField;
        
        private string seatClassField;
        
        private string startDateField;
        
        private string supplyOfficeNoField;
        
        private string ticketSpeedField;
        
        private string vtWorkTimeField;
        
        private string workTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string airlineCode {
            get {
                return this.airlineCodeField;
            }
            set {
                this.airlineCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arrivalExclude {
            get {
                return this.arrivalExcludeField;
            }
            set {
                this.arrivalExcludeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double commisionMoney {
            get {
                return this.commisionMoneyField;
            }
            set {
                this.commisionMoneyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool commisionMoneySpecified {
            get {
                return this.commisionMoneyFieldSpecified;
            }
            set {
                this.commisionMoneyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float commisionPoint {
            get {
                return this.commisionPointField;
            }
            set {
                this.commisionPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool commisionPointSpecified {
            get {
                return this.commisionPointFieldSpecified;
            }
            set {
                this.commisionPointFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string departureExclude {
            get {
                return this.departureExcludeField;
            }
            set {
                this.departureExcludeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string expiredDate {
            get {
                return this.expiredDateField;
            }
            set {
                this.expiredDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string flightCourse {
            get {
                return this.flightCourseField;
            }
            set {
                this.flightCourseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string flightCycle {
            get {
                return this.flightCycleField;
            }
            set {
                this.flightCycleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string flightNoExclude {
            get {
                return this.flightNoExcludeField;
            }
            set {
                this.flightNoExcludeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string flightNoIncluding {
            get {
                return this.flightNoIncludingField;
            }
            set {
                this.flightNoIncludingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int needSwitchPNR {
            get {
                return this.needSwitchPNRField;
            }
            set {
                this.needSwitchPNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool needSwitchPNRSpecified {
            get {
                return this.needSwitchPNRFieldSpecified;
            }
            set {
                this.needSwitchPNRFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param3 {
            get {
                return this.param3Field;
            }
            set {
                this.param3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param4 {
            get {
                return this.param4Field;
            }
            set {
                this.param4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string policyBelongToFlag {
            get {
                return this.policyBelongToFlagField;
            }
            set {
                this.policyBelongToFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int policyId {
            get {
                return this.policyIdField;
            }
            set {
                this.policyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool policyIdSpecified {
            get {
                return this.policyIdFieldSpecified;
            }
            set {
                this.policyIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string policyType {
            get {
                return this.policyTypeField;
            }
            set {
                this.policyTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string printTicketExpiredDate {
            get {
                return this.printTicketExpiredDateField;
            }
            set {
                this.printTicketExpiredDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string printTicketStartDate {
            get {
                return this.printTicketStartDateField;
            }
            set {
                this.printTicketStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int productType {
            get {
                return this.productTypeField;
            }
            set {
                this.productTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productTypeSpecified {
            get {
                return this.productTypeFieldSpecified;
            }
            set {
                this.productTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string routeType {
            get {
                return this.routeTypeField;
            }
            set {
                this.routeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string seatClass {
            get {
                return this.seatClassField;
            }
            set {
                this.seatClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string supplyOfficeNo {
            get {
                return this.supplyOfficeNoField;
            }
            set {
                this.supplyOfficeNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ticketSpeed {
            get {
                return this.ticketSpeedField;
            }
            set {
                this.ticketSpeedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vtWorkTime {
            get {
                return this.vtWorkTimeField;
            }
            set {
                this.vtWorkTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string workTime {
            get {
                return this.workTimeField;
            }
            set {
                this.workTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getPolicyByPnrTxtReply))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/")]
    public abstract partial class abstractLiantuoReply {
        
        private string returnCodeField;
        
        private string returnMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string returnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getpolicybypnrtxt.b2b.service.version1_0.webservice.model.ltips.com/")]
    public partial class getPolicyByPnrTxtReply : abstractLiantuoReply {
        
        private string param1Field;
        
        private string param2Field;
        
        private string param3Field;
        
        private string param4Field;
        
        private wsPolicyData[] policyListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param3 {
            get {
                return this.param3Field;
            }
            set {
                this.param3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param4 {
            get {
                return this.param4Field;
            }
            set {
                this.param4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("policyList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public wsPolicyData[] policyList {
            get {
                return this.policyListField;
            }
            set {
                this.policyListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getPolicyByPnrTxtCompletedEventHandler(object sender, getPolicyByPnrTxtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPolicyByPnrTxtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPolicyByPnrTxtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getPolicyByPnrTxtReply Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getPolicyByPnrTxtReply)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591