//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChinaPay.B3B.Service.ExternalPlatform.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://wstest.51book.com:55779/ltips/services/createOrderByRtPatService1.0")]
        public string ChinaPay_B3B_Service_ExternalPlatform__51bookCreateOrder_CreateOrderByRtPatServiceImpl_1_0Service {
            get {
                return ((string)(this["ChinaPay_B3B_Service_ExternalPlatform__51bookCreateOrder_CreateOrderByRtPatServic" +
                    "eImpl_1_0Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://wstest.51book.com:55779/ltips/services/getPolicyByPnrTxtService1.0")]
        public string ChinaPay_B3B_Service_ExternalPlatform__51bookMatchPolicy_GetPolicyByPnrTxtServiceImpl_1_0Service {
            get {
                return ((string)(this["ChinaPay_B3B_Service_ExternalPlatform__51bookMatchPolicy_GetPolicyByPnrTxtService" +
                    "Impl_1_0Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://wstest.51book.com:55779/ltips/services/payService1.0")]
        public string ChinaPay_B3B_Service_ExternalPlatform__51bookAutoPay_PayServiceImpl_1_0Service {
            get {
                return ((string)(this["ChinaPay_B3B_Service_ExternalPlatform__51bookAutoPay_PayServiceImpl_1_0Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://wstest.51book.com:55779/ltips/services/getPaymentUrlService1.0")]
        public string ChinaPay_B3B_Service_ExternalPlatform__51bookManualPay_GetPaymentUrlServiceImpl_1_0Service {
            get {
                return ((string)(this["ChinaPay_B3B_Service_ExternalPlatform__51bookManualPay_GetPaymentUrlServiceImpl_1" +
                    "_0Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://wstest.51book.com:55779/ltips/services/cancelOrderService1.0")]
        public string ChinaPay_B3B_Service_ExternalPlatform__51bookCancelOrder_CancelOrderServiceImpl_1_0Service {
            get {
                return ((string)(this["ChinaPay_B3B_Service_ExternalPlatform__51bookCancelOrder_CancelOrderServiceImpl_1" +
                    "_0Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://wstest.51book.com:55779/ltips/services/getOrderByOrderNoService1.0")]
        public string ChinaPay_B3B_Service_ExternalPlatform__51bookOrderDetail_GetOrderByOrderNoServiceImpl_1_0Service {
            get {
                return ((string)(this["ChinaPay_B3B_Service_ExternalPlatform__51bookOrderDetail_GetOrderByOrderNoService" +
                    "Impl_1_0Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://118.114.245.44:9005/BenefitInterface.asmx")]
        public string ChinaPay_B3B_Service_ExternalPlatform__517Na_BenefitInterface {
            get {
                return ((string)(this["ChinaPay_B3B_Service_ExternalPlatform__517Na_BenefitInterface"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www2.yeexing.com/CXF/services/IBEService")]
        public string ChinaPay_B3B_Service_ExternalPlatform_Yeexing_IBEService {
            get {
                return ((string)(this["ChinaPay_B3B_Service_ExternalPlatform_Yeexing_IBEService"]));
            }
        }
    }
}
